### ISSUE TITLE
How to make a eggman boss with Sonic Realms.

### ISSUE THREAD

**Issue by El-Misterioso-Team-Games** [mdechatech/Sonic-Realms#6]
please I need your help

**Comment by Foxeh89** [comment]
1. use invisible walls to keep the player in a spot where you want them to fight the boss.
2. make sure the camera locks/waits/focuses on the area of the fight.
3. on your eggman boss, make sure you use the badnick health and i think maybe have the health get loss when the sonic collider *ENTERS* the enemy collision. if it's on stay, it'll run through their health really fast instead of taking only 1 hit.


i havent made a boss yet, so i dont got any definite explanation. but this is how i'd approach it
